### ISSUE TITLE
Missed test in CI

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane#113]
Commit 7ca39e7014080b9063599402badd04e4c27f3bf8 was needed to revert an erroneously removed dependency.

@Lut99, which tests broke? If I run `cargo test --workspace` on the broken change, I don't see a failed tests. Is there another test-suite I am not aware of?

Let's make sure whatever it is, is covered inside CI so we can prevent it in the future.

**Comment by Lut99** [comment]
There was one in `brane-exe`, `test_threads()` in `threads.rs`. But it didn't show up because it's conditionally compiled on the `test_logging`-feature :) It should when you hit `cargo test --all-features --workspace` (without the flag, `cargo test` doesn't enable any features!).

I noticed it because I have `rust-analyzer` always enable all features. Makes it harder to see whether features can be cleanly disabled, but at least it will analyze all code.

When I just started, the CI/CD definitely had a lot of intense flags setup in testing, also doing `--all-targets` I think. But maybe it's gotten lost in translation somewhere? If so, `make.py test-units` should have a clone of that command (to allow local testing such that the CI/CD agrees).

**Comment by DanielVoogsgerd** [comment]
I think you mean something like Cargo hack. It has something like `--feature-powerset`. I use it in the CI of policy reasoner and should have used it in this repo as well. I will add that, thanks!

Also thanks for the RA tip, I will look into that, seems like the best setting indeed. Having half our my code greyed out at times annoying
