### ISSUE TITLE
Brane-oas

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane#136]
Brane-oas, I think the openapi specification, has unmaintained dependencies. What is the state of this workspace member? Is it completely obsolete/unused, or is there some place where it is either in use or close to providing some value?

If it isn't, I suggest we remove it. Git history is always there if somebody is interested in reviving it. It might seem harsh, but I am really trying to cut down on tech debt and maintenance burden.

**Comment by Lut99** [comment]
Yeah sure. I haven't looked at this in ages. It used to be there to write containers using the OpenAPI specification, but it's kind of become obsolete since we have containers that aren't supposed to use the internet.

I think the idea is to have it here again after the heat death of the universe. So I'm all for removing it. But maybe, is it somehow possible to document that there exist something on this? I don't think many people picking this up will think of looking at Brane enormous git history, lol

**Comment by DanielVoogsgerd** [comment]
Yeah, sounds like a plan. I can make a "graveyard" of sorts in the overview package. Where we just mention that `x` has been removed in commit `y`.

**Comment by Lut99** [comment]
Good idea!
