### ISSUE TITLE
Git structure

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane#94]
I was wondering what the structure was with regards to the different branches. We use feature branches that merge into develop, but how does master come into play here. Is this the latest released version and do tags reference commits on master, is it some staging area when stabilizing a new release, etc?

We should probably also rename it to main anyway, at least to stay consistent with the other repositories.

**Comment by Lut99** [comment]
So:
- I agree with the naming. Already done, the default branch is called `main`.
- `develop` is essentially a feature-agnostic feature branch. I.e., I used to do work there and then push it to `main` whenever it "works". So basically, `main` is always demo-ready.
   - But I think it's obsolete if we use actual feature branches. Which I'm in favor of.

So: closing, because we already renamed. I'll remove `develop` once all PRs pointing to it have been processed.
